version: 0.0
os: linux
files:
  - source: target/shopping-cart-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/ekart

permissions:
  - object: /home/ec2-user/ekart
    pattern: "**"
    mode: 755
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
