version: 0.0
os: linux
files:
  - source: target/shopping-cart-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
