version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "⬇️ Installing Maven, unzip & AWS CLI..."
      - apt-get update
      - apt-get install -y maven unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - echo "✅ Installed Maven and AWS CLI"

  pre_build:
    commands:
      - echo "📂 Current directory:"
      - pwd
      - echo "📂 Files:"
      - ls -l

  build:
    commands:
      - echo "🚧 Building Spring Boot project..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "🚀 Uploading JAR to S3..."
      - aws s3 cp target/*.jar s3://myekarts3/

artifacts:
  files:
    - target/*.jar
