version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Pre-Build Phase: Listing all files
      - ls -R

  build:
    commands:
      - echo Entering Ekart-main directory...
      - cd Ekart-main
      - echo Running Maven build...
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Uploading JAR file to S3...
      - aws s3 cp target/*.jar s3://myekarts3/

artifacts:
  files:
    - Ekart-main/target/*.jar

