version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "📂 Verifying current directory"
      - pwd
      - echo "📂 Listing files"
      - ls -l

  build:
    commands:
      - echo "🚧 Building Spring Boot project..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "🚀 Uploading JAR to S3..."
      - aws s3 cp target/*.jar s3://myekarts3/

artifacts:
  files:
    - target/*.jar
