version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - apt-get update
      - apt-get install -y maven

  build:
    commands:
      - echo "Building the application..."
      - mvn clean package -DskipTests
      - echo "Build complete."

  post_build:
    commands:
      - echo "Zipping deployment files..."
      - mkdir -p deploy
      - cp target/shopping-cart-0.0.1-SNAPSHOT.jar deploy/
      - cp appspec.yml deploy/
      - mkdir -p deploy/scripts
      - cp scripts/start_server.sh deploy/scripts/
artifacts:
  files:
    - deploy/**/*
