version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Navigating to project directory..."
      - cd Ekart-main
      - echo "Listing files in Ekart-main to verify:"
      - ls -l

  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Uploading JAR to S3..."
      - aws s3 cp target/*.jar s3://myekarts3/

artifacts:
  files:
    - Ekart-main/target/*.jar


