version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Showing project structure
      - ls -al
      - find . -name "pom.xml"
  build:
    commands:
      - echo Moving into the directory with pom.xml
      - cd Ekart-main/Ekart-main
      - echo Building the Spring Boot app
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Uploading JAR to S3
      - aws s3 cp target/*.jar s3://myekarts3/
artifacts:
  files:
    - Ekart-main/Ekart-main/target/*.jar
